export const doctors = [
  {
    id: 1,
    name: "Dr. A. K. Singh",
    city: "Mumbai",
    location: "Andheri",
    Specialization: "Cardiologist",
    rating: "4",
    experience: "15",
  },
  {
    id: 2,
    name: "Dr. B. R. Sharma",
    city: "Delhi",
    location: "Connaught Place",
    Specialization: "Dermatologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 3,
    name: "Dr. C. L. Verma",
    city: "Bangalore",
    location: "Koramangala",
    Specialization: "Neurologist",
    rating: "3",
    experience: "8",
  },
  {
    id: 4,
    name: "Dr. D. M. Reddy",
    city: "Hyderabad",
    location: "Banjara Hills",
    Specialization: "Orthopedic",
    rating: "4",
    experience: "12",
  },
  {
    id: 5,
    name: "Dr. E. S. Rao",
    city: "Chennai",
    location: "Adyar",
    Specialization: "Pediatrician",
    rating: "5",
    experience: "9",
  },
  {
    id: 6,
    name: "Dr. F. K. Patel",
    city: "Ahmedabad",
    location: "Navrangpura",
    Specialization: "Ophthalmologist",
    rating: "4",
    experience: "13",
  },
  {
    id: 7,
    name: "Dr. G. N. Iyer",
    city: "Pune",
    location: "Kothrud",
    Specialization: "Gynecologist",
    rating: "5",
    experience: "11",
  },
  {
    id: 8,
    name: "Dr. H. J. Sinha",
    city: "Kolkata",
    location: "Salt Lake",
    Specialization: "Oncologist",
    rating: "4",
    experience: "14",
  },
  {
    id: 9,
    name: "Dr. I. P. Roy",
    city: "Jaipur",
    location: "Malviya Nagar",
    Specialization: "Psychiatrist",
    rating: "3",
    experience: "7",
  },
  {
    id: 10,
    name: "Dr. J. L. Mehta",
    city: "Lucknow",
    location: "Gomti Nagar",
    Specialization: "Endocrinologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 11,
    name: "Dr. K. V. Thakur",
    city: "Patna",
    location: "Kankarbagh",
    Specialization: "Cardiologist",
    rating: "4",
    experience: "15",
  },
  {
    id: 12,
    name: "Dr. L. S. Khan",
    city: "Indore",
    location: "Vijay Nagar",
    Specialization: "Dermatologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 13,
    name: "Dr. M. K. Yadav",
    city: "Bhopal",
    location: "Arera Colony",
    Specialization: "Neurologist",
    rating: "3",
    experience: "8",
  },
  {
    id: 14,
    name: "Dr. N. P. Mishra",
    city: "Chandigarh",
    location: "Sector 17",
    Specialization: "Orthopedic",
    rating: "4",
    experience: "12",
  },
  {
    id: 15,
    name: "Dr. O. R. Gupta",
    city: "Guwahati",
    location: "Pan Bazaar",
    Specialization: "Pediatrician",
    rating: "5",
    experience: "9",
  },
  {
    id: 16,
    name: "Dr. P. S. Joshi",
    city: "Kochi",
    location: "Edappally",
    Specialization: "Ophthalmologist",
    rating: "4",
    experience: "13",
  },
  {
    id: 17,
    name: "Dr. Q. K. Nair",
    city: "Thiruvananthapuram",
    location: "Kowdiar",
    Specialization: "Gynecologist",
    rating: "5",
    experience: "11",
  },
  {
    id: 18,
    name: "Dr. R. M. Das",
    city: "Bhubaneswar",
    location: "Saheed Nagar",
    Specialization: "Oncologist",
    rating: "4",
    experience: "14",
  },
  {
    id: 19,
    name: "Dr. S. K. Agarwal",
    city: "Dehradun",
    location: "Rajpur Road",
    Specialization: "Psychiatrist",
    rating: "3",
    experience: "7",
  },
  {
    id: 20,
    name: "Dr. T. R. Kulkarni",
    city: "Nagpur",
    location: "Sadar",
    Specialization: "Endocrinologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 21,
    name: "Dr. U. L. Deshmukh",
    city: "Raipur",
    location: "Pandri",
    Specialization: "Cardiologist",
    rating: "4",
    experience: "15",
  },
  {
    id: 22,
    name: "Dr. V. S. Chauhan",
    city: "Ranchi",
    location: "Morabadi",
    Specialization: "Dermatologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 23,
    name: "Dr. W. P. Jain",
    city: "Shimla",
    location: "Mall Road",
    Specialization: "Neurologist",
    rating: "3",
    experience: "8",
  },
  {
    id: 24,
    name: "Dr. X. K. Roy",
    city: "Shillong",
    location: "Laitumkhrah",
    Specialization: "Orthopedic",
    rating: "4",
    experience: "12",
  },
  {
    id: 25,
    name: "Dr. Y. R. Tiwari",
    city: "Imphal",
    location: "Thangmeiband",
    Specialization: "Pediatrician",
    rating: "5",
    experience: "9",
  },
  {
    id: 26,
    name: "Dr. Z. M. Naidu",
    city: "Agra",
    location: "Sikandra",
    Specialization: "Ophthalmologist",
    rating: "4",
    experience: "13",
  },
  {
    id: 27,
    name: "Dr. A. N. Chawla",
    city: "Ajmer",
    location: "Kaisar Ganj",
    Specialization: "Gynecologist",
    rating: "5",
    experience: "11",
  },
  {
    id: 28,
    name: "Dr. B. P. Thakur",
    city: "Aligarh",
    location: "Civil Lines",
    Specialization: "Oncologist",
    rating: "4",
    experience: "14",
  },
  {
    id: 29,
    name: "Dr. C. L. Sethi",
    city: "Amritsar",
    location: "Ranjit Avenue",
    Specialization: "Psychiatrist",
    rating: "3",
    experience: "7",
  },
  {
    id: 30,
    name: "Dr. D. K. Mehra",
    city: "Aurangabad",
    location: "CIDCO",
    Specialization: "Endocrinologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 31,
    name: "Dr. E. P. Khurana",
    city: "Bareilly",
    location: "Civil Lines",
    Specialization: "Cardiologist",
    rating: "4",
    experience: "15",
  },
  {
    id: 32,
    name: "Dr. F. R. Aggarwal",
    city: "Belgaum",
    location: "Tilakwadi",
    Specialization: "Dermatologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 33,
    name: "Dr. G. N. Reddy",
    city: "Bhavnagar",
    location: "Waghawadi Road",
    Specialization: "Neurologist",
    rating: "3",
    experience: "8",
  },
  {
    id: 34,
    name: "Dr. H. K. Rao",
    city: "Bikaner",
    location: "Rani Bazar",
    Specialization: "Orthopedic",
    rating: "4",
    experience: "12",
  },
  {
    id: 35,
    name: "Dr. I. P. Chaudhary",
    city: "Bilaspur",
    location: "Link Road",
    Specialization: "Pediatrician",
    rating: "5",
    experience: "9",
  },
  {
    id: 36,
    name: "Dr. J. L. Bhatia",
    city: "Bokaro",
    location: "Sector 4",
    Specialization: "Ophthalmologist",
    rating: "4",
    experience: "13",
  },
  {
    id: 37,
    name: "Dr. K. M. Naik",
    city: "Cuttack",
    location: "Buxi Bazar",
    Specialization: "Gynecologist",
    rating: "5",
    experience: "11",
  },
  {
    id: 38,
    name: "Dr. L. N. Roy",
    city: "Dhanbad",
    location: "Saraidhela",
    Specialization: "Oncologist",
    rating: "4",
    experience: "14",
  },
  {
    id: 39,
    name: "Dr. M. P. Singh",
    city: "Dharamshala",
    location: "Kotwali Bazaar",
    Specialization: "Psychiatrist",
    rating: "3",
    experience: "7",
  },
  {
    id: 40,
    name: "Dr. N. Q. Sharma",
    city: "Faridabad",
    location: "Sector 15",
    Specialization: "Endocrinologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 41,
    name: "Dr. O. R. Mathur",
    city: "Gwalior",
    location: "Phoolbagh",
    Specialization: "Cardiologist",
    rating: "4",
    experience: "15",
  },
  {
    id: 42,
    name: "Dr. P. S. Desai",
    city: "Haridwar",
    location: "Shivalik Nagar",
    Specialization: "Dermatologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 43,
    name: "Dr. Q. T. Gupta",
    city: "Hubli",
    location: "Vidya Nagar",
    Specialization: "Neurologist",
    rating: "3",
    experience: "8",
  },
  {
    id: 44,
    name: "Dr. R. V. Shetty",
    city: "Jabalpur",
    location: "Napier Town",
    Specialization: "Orthopedic",
    rating: "4",
    experience: "12",
  },
  {
    id: 45,
    name: "Dr. S. W. Rao",
    city: "Jalandhar",
    location: "Model Town",
    Specialization: "Pediatrician",
    rating: "5",
    experience: "9",
  },
  {
    id: 46,
    name: "Dr. T. X. Dubey",
    city: "Jammu",
    location: "Gandhi Nagar",
    Specialization: "Ophthalmologist",
    rating: "4",
    experience: "13",
  },
  {
    id: 47,
    name: "Dr. U. Y. Singh",
    city: "Jamshedpur",
    location: "Sakchi",
    Specialization: "Gynecologist",
    rating: "5",
    experience: "11",
  },
  {
    id: 48,
    name: "Dr. V. Z. Reddy",
    city: "Jhansi",
    location: "Civil Lines",
    Specialization: "Oncologist",
    rating: "4",
    experience: "14",
  },
  {
    id: 49,
    name: "Dr. W. K. Pandey",
    city: "Kakinada",
    location: "Ramanayyapeta",
    Specialization: "Psychiatrist",
    rating: "3",
    experience: "7",
  },
  {
    id: 50,
    name: "Dr. X. L. Mehta",
    city: "Kannur",
    location: "Talap",
    Specialization: "Endocrinologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 51,
    name: "Dr. Y. M. Nair",
    city: "Kanyakumari",
    location: "Vivekananda Kendra",
    Specialization: "Cardiologist",
    rating: "4",
    experience: "15",
  },
  {
    id: 52,
    name: "Dr. Z. N. Sethi",
    city: "Karimnagar",
    location: "Mukarrampura",
    Specialization: "Dermatologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 53,
    name: "Dr. A. O. Khan",
    city: "Kolhapur",
    location: "Shahupuri",
    Specialization: "Neurologist",
    rating: "3",
    experience: "8",
  },
  {
    id: 54,
    name: "Dr. B. P. Sharma",
    city: "Kota",
    location: "Vigyan Nagar",
    Specialization: "Orthopedic",
    rating: "4",
    experience: "12",
  },
  {
    id: 55,
    name: "Dr. C. Q. Patel",
    city: "Kozhikode",
    location: "Mavoor Road",
    Specialization: "Pediatrician",
    rating: "5",
    experience: "9",
  },
  {
    id: 56,
    name: "Dr. D. R. Singh",
    city: "Ludhiana",
    location: "Sarabha Nagar",
    Specialization: "Ophthalmologist",
    rating: "4",
    experience: "13",
  },
  {
    id: 57,
    name: "Dr. E. S. Tiwari",
    city: "Madurai",
    location: "KK Nagar",
    Specialization: "Gynecologist",
    rating: "5",
    experience: "11",
  },
  {
    id: 58,
    name: "Dr. F. T. Yadav",
    city: "Mangalore",
    location: "Bejai",
    Specialization: "Oncologist",
    rating: "4",
    experience: "14",
  },
  {
    id: 59,
    name: "Dr. G. U. Verma",
    city: "Meerut",
    location: "Shastri Nagar",
    Specialization: "Psychiatrist",
    rating: "3",
    experience: "7",
  },
  {
    id: 60,
    name: "Dr. H. V. Choudhary",
    city: "Moradabad",
    location: "Civil Lines",
    Specialization: "Endocrinologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 61,
    name: "Dr. I. W. Singh",
    city: "Mysore",
    location: "VV Mohalla",
    Specialization: "Cardiologist",
    rating: "4",
    experience: "15",
  },
  {
    id: 62,
    name: "Dr. J. X. Naik",
    city: "Nagpur",
    location: "Dharampeth",
    Specialization: "Dermatologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 63,
    name: "Dr. K. Y. Reddy",
    city: "Nanded",
    location: "Vishnupuri",
    Specialization: "Neurologist",
    rating: "3",
    experience: "8",
  },
  {
    id: 64,
    name: "Dr. L. Z. Rao",
    city: "Nashik",
    location: "College Road",
    Specialization: "Orthopedic",
    rating: "4",
    experience: "12",
  },
  {
    id: 65,
    name: "Dr. M. A. Bhatia",
    city: "Panaji",
    location: "Patto",
    Specialization: "Pediatrician",
    rating: "5",
    experience: "9",
  },
  {
    id: 66,
    name: "Dr. N. B. Choudhary",
    city: "Patiala",
    location: "Urban Estate",
    Specialization: "Ophthalmologist",
    rating: "4",
    experience: "13",
  },
  {
    id: 67,
    name: "Dr. O. C. Singh",
    city: "Pondicherry",
    location: "Mission Street",
    Specialization: "Gynecologist",
    rating: "5",
    experience: "11",
  },
  {
    id: 68,
    name: "Dr. P. D. Nair",
    city: "Pune",
    location: "Shivaji Nagar",
    Specialization: "Oncologist",
    rating: "4",
    experience: "14",
  },
  {
    id: 69,
    name: "Dr. Q. E. Desai",
    city: "Raipur",
    location: "Shankar Nagar",
    Specialization: "Psychiatrist",
    rating: "3",
    experience: "7",
  },
  {
    id: 70,
    name: "Dr. R. F. Shetty",
    city: "Rajahmundry",
    location: "Danavaipeta",
    Specialization: "Endocrinologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 71,
    name: "Dr. S. G. Sharma",
    city: "Rajkot",
    location: "Kalawad Road",
    Specialization: "Cardiologist",
    rating: "4",
    experience: "15",
  },
  {
    id: 72,
    name: "Dr. T. H. Dubey",
    city: "Ranchi",
    location: "Kanke Road",
    Specialization: "Dermatologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 73,
    name: "Dr. U. I. Gupta",
    city: "Rourkela",
    location: "Udit Nagar",
    Specialization: "Neurologist",
    rating: "3",
    experience: "8",
  },
  {
    id: 74,
    name: "Dr. V. J. Mathur",
    city: "Saharanpur",
    location: "Janakpuri",
    Specialization: "Orthopedic",
    rating: "4",
    experience: "12",
  },
  {
    id: 75,
    name: "Dr. W. K. Desai",
    city: "Salem",
    location: "Gugai",
    Specialization: "Pediatrician",
    rating: "5",
    experience: "9",
  },
  {
    id: 76,
    name: "Dr. X. L. Tiwari",
    city: "Shimla",
    location: "Lakkar Bazar",
    Specialization: "Ophthalmologist",
    rating: "4",
    experience: "13",
  },
  {
    id: 77,
    name: "Dr. Y. M. Naik",
    city: "Siliguri",
    location: "Sevoke Road",
    Specialization: "Gynecologist",
    rating: "5",
    experience: "11",
  },
  {
    id: 78,
    name: "Dr. Z. N. Sethi",
    city: "Solapur",
    location: "Park Chowk",
    Specialization: "Oncologist",
    rating: "4",
    experience: "14",
  },
  {
    id: 79,
    name: "Dr. A. O. Khan",
    city: "Sonipat",
    location: "Sector 14",
    Specialization: "Psychiatrist",
    rating: "3",
    experience: "7",
  },
  {
    id: 80,
    name: "Dr. B. P. Sharma",
    city: "Surat",
    location: "Adajan",
    Specialization: "Endocrinologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 81,
    name: "Dr. C. Q. Patel",
    city: "Thane",
    location: "Kopri",
    Specialization: "Cardiologist",
    rating: "4",
    experience: "15",
  },
  {
    id: 82,
    name: "Dr. D. R. Singh",
    city: "Tiruchirappalli",
    location: "Srirangam",
    Specialization: "Dermatologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 83,
    name: "Dr. E. S. Tiwari",
    city: "Tirunelveli",
    location: "Vannarpettai",
    Specialization: "Neurologist",
    rating: "3",
    experience: "8",
  },
  {
    id: 84,
    name: "Dr. F. T. Yadav",
    city: "Udaipur",
    location: "Sector 11",
    Specialization: "Orthopedic",
    rating: "4",
    experience: "12",
  },
  {
    id: 85,
    name: "Dr. G. U. Verma",
    city: "Ujjain",
    location: "Freeganj",
    Specialization: "Pediatrician",
    rating: "5",
    experience: "9",
  },
  {
    id: 86,
    name: "Dr. H. V. Choudhary",
    city: "Vadodara",
    location: "Alkapuri",
    Specialization: "Ophthalmologist",
    rating: "4",
    experience: "13",
  },
  {
    id: 87,
    name: "Dr. I. W. Singh",
    city: "Varanasi",
    location: "Sigra",
    Specialization: "Gynecologist",
    rating: "5",
    experience: "11",
  },
  {
    id: 88,
    name: "Dr. J. X. Naik",
    city: "Vellore",
    location: "Katpadi",
    Specialization: "Oncologist",
    rating: "4",
    experience: "14",
  },
  {
    id: 89,
    name: "Dr. K. Y. Reddy",
    city: "Vijayawada",
    location: "Moghalrajpuram",
    Specialization: "Psychiatrist",
    rating: "3",
    experience: "7",
  },
  {
    id: 90,
    name: "Dr. L. Z. Rao",
    city: "Visakhapatnam",
    location: "Siripuram",
    Specialization: "Endocrinologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 91,
    name: "Dr. M. A. Bhatia",
    city: "Warangal",
    location: "Hanamkonda",
    Specialization: "Cardiologist",
    rating: "4",
    experience: "15",
  },
  {
    id: 92,
    name: "Dr. N. B. Choudhary",
    city: "Yamunanagar",
    location: "Model Town",
    Specialization: "Dermatologist",
    rating: "5",
    experience: "10",
  },
  {
    id: 93,
    name: "Dr. Sanjay Kapoor",
    city: "New Delhi",
    location: "Connaught Place",
    Specialization: "General Physician",
    rating: "4.2",
    experience: "12",
  },
  {
    id: 94,
    name: "Dr. Nisha Singh",
    city: "New Delhi",
    location: "Dwarka",
    Specialization: "Dermatologist",
    rating: "4.5",
    experience: "9",
  },
  {
    id: 95,
    name: "Dr. Rajesh Gupta",
    city: "Mumbai",
    location: "Powai",
    Specialization: "Neurologist",
    rating: "4.3",
    experience: "11",
  },
  {
    id: 96,
    name: "Dr. Anjali Patel",
    city: "Bangalore",
    location: "Koramangala",
    Specialization: "Gynecologist",
    rating: "4.6",
    experience: "10",
  },
  {
    id: 97,
    name: "Dr. Ramesh Kumar",
    city: "Chennai",
    location: "Anna Nagar",
    Specialization: "Pediatrician",
    rating: "4.4",
    experience: "14",
  },
  {
    id: 98,
    name: "Dr. Akash Sharma",
    city: "Hyderabad",
    location: "Banjara Hills",
    Specialization: "Orthopedic",
    rating: "4.7",
    experience: "18",
  },
  {
    id: 99,
    name: "Dr. Priya Reddy",
    city: "Kolkata",
    location: "Park Street",
    Specialization: "Ophthalmologist",
    rating: "4.9",
    experience: "22",
  },
  {
    id: 100,
    name: "Dr. Amit Kumar",
    city: "Pune",
    location: "Kothrud",
    Specialization: "Dentist",
    rating: "4.8",
    experience: "16",
  },
  {
    id: 101,
    name: "Dr. Neha Singh",
    city: "Ahmedabad",
    location: "Gurukul",
    Specialization: "ENT Specialist",
    rating: "4.6",
    experience: "13",
  },

  {
    id: 102,
    name: "Dr. Rajesh Patel",
    city: "New Delhi",
    location: "Rajouri Garden",
    Specialization: "General Physician",
    rating: "4.5",
    experience: "14",
  },
  {
    id: 103,
    name: "Dr. Nandini Rao",
    city: "Gurgaon",
    location: "DLF Phase 3",
    Specialization: "Dermatologist",
    rating: "4.7",
    experience: "16",
  },
  {
    id: 104,
    name: "Dr. Suresh Menon",
    city: "Noida",
    location: "Sector 62",
    Specialization: "Neurologist",
    rating: "4.8",
    experience: "20",
  },
  {
    id: 105,
    name: "Dr. Pooja Sharma",
    city: "Mumbai",
    location: "Bandra",
    Specialization: "Gynecologist",
    rating: "4.6",
    experience: "15",
  },
  {
    id: 106,
    name: "Dr. Ramesh Gupta",
    city: "Bangalore",
    location: "Indiranagar",
    Specialization: "Pediatrician",
    rating: "4.9",
    experience: "21",
  },
  {
    id: 107,
    name: "Dr. Siddharth Joshi",
    city: "Chennai",
    location: "Anna Nagar",
    Specialization: "Orthopedic",
    rating: "4.7",
    experience: "18",
  },
  {
    id: 108,
    name: "Dr. Meera Nair",
    city: "Hyderabad",
    location: "Madhapur",
    Specialization: "Ophthalmologist",
    rating: "4.9",
    experience: "23",
  },
  {
    id: 109,
    name: "Dr. Karthik Reddy",
    city: "Kolkata",
    location: "Salt Lake",
    Specialization: "Dentist",
    rating: "4.8",
    experience: "17",
  },
  {
    id: 110,
    name: "Dr. Anjali Sinha",
    city: "Pune",
    location: "Swargate",
    Specialization: "ENT Specialist",
    rating: "4.6",
    experience: "14",
  },
  {
    id: 111,
    name: "Dr. Sanjay Gupta",
    city: "Ahmedabad",
    location: "Maninagar",
    Specialization: "General Physician",
    rating: "4.5",
    experience: "15",
  },
  {
    id: 112,
    name: "Dr. Neha Singh",
    city: "New Delhi",
    location: "Dwarka",
    Specialization: "Dermatologist",
    rating: "4.6",
    experience: "16",
  },
  {
    id: 113,
    name: "Dr. Vikram Rao",
    city: "Gurgaon",
    location: "Sohna Road",
    Specialization: "Neurologist",
    rating: "4.7",
    experience: "18",
  },
  {
    id: 114,
    name: "Dr. Anusha Menon",
    city: "Noida",
    location: "Sector 18",
    Specialization: "Gynecologist",
    rating: "4.8",
    experience: "21",
  },
  {
    id: 115,
    name: "Dr. Mohan Sharma",
    city: "Mumbai",
    location: "Powai",
    Specialization: "Pediatrician",
    rating: "4.9",
    experience: "22",
  },
  {
    id: 116,
    name: "Dr. Nisha Joshi",
    city: "Bangalore",
    location: "Koramangala",
    Specialization: "Orthopedic",
    rating: "4.7",
    experience: "19",
  },
  {
    id: 117,
    name: "Dr. Vivek Nair",
    city: "Chennai",
    location: "T Nagar",
    Specialization: "Ophthalmologist",
    rating: "4.9",
    experience: "24",
  },
  {
    id: 118,
    name: "Dr. Priya Reddy",
    city: "Hyderabad",
    location: "Kukatpally",
    Specialization: "Dentist",
    rating: "4.8",
    experience: "18",
  },
  {
    id: 119,
    name: "Dr. Rahul Sinha",
    city: "Kolkata",
    location: "Park Street",
    Specialization: "ENT Specialist",
    rating: "4.6",
    experience: "15",
  },
  {
    id: 120,
    name: "Dr. Ananya Patel",
    city: "Pune",
    location: "Kothrud",
    Specialization: "General Physician",
    rating: "4.5",
    experience: "16",
  },
  {
    id: 121,
    name: "Dr. Arvind Gupta",
    city: "Ahmedabad",
    location: "Satellite",
    Specialization: "Dermatologist",
    rating: "4.6",
    experience: "17",
  },

  {
    id: 130,
    name: "Dr. Rakesh Kumar",
    city: "New Delhi",
    location: "Rohini",
    Specialization: "General Physician",
    rating: "4.5",
    experience: "18",
  },
  {
    id: 131,
    name: "Dr. Meera Kapoor",
    city: "Gurgaon",
    location: "Sector 14",
    Specialization: "Gynecologist",
    rating: "4.7",
    experience: "20",
  },
  {
    id: 132,
    name: "Dr. Sanjay Gupta",
    city: "Noida",
    location: "Sector 62",
    Specialization: "Cardiologist",
    rating: "4.8",
    experience: "22",
  },
  {
    id: 133,
    name: "Dr. Anjali Sharma",
    city: "Mumbai",
    location: "Bandra",
    Specialization: "Neurologist",
    rating: "4.9",
    experience: "23",
  },
  {
    id: 134,
    name: "Dr. Sameer Patel",
    city: "Bangalore",
    location: "Indiranagar",
    Specialization: "Orthopedic",
    rating: "4.7",
    experience: "20",
  },
  {
    id: 135,
    name: "Dr. Shalini Reddy",
    city: "Chennai",
    location: "Anna Nagar",
    Specialization: "Ophthalmologist",
    rating: "4.9",
    experience: "25",
  },
  {
    id: 136,
    name: "Dr. Manoj Kumar",
    city: "Hyderabad",
    location: "Madhapur",
    Specialization: "Dentist",
    rating: "4.8",
    experience: "19",
  },
  {
    id: 137,
    name: "Dr. Swati Joshi",
    city: "Kolkata",
    location: "Salt Lake",
    Specialization: "Pediatrician",
    rating: "4.6",
    experience: "16",
  },
  {
    id: 138,
    name: "Dr. Ajay Singh",
    city: "Pune",
    location: "Wakad",
    Specialization: "ENT Specialist",
    rating: "4.5",
    experience: "17",
  },
  {
    id: 139,
    name: "Dr. Priyanka Sharma",
    city: "Ahmedabad",
    location: "Maninagar",
    Specialization: "General Physician",
    rating: "4.6",
    experience: "18",
  },
  {
    id: 140,
    name: "Dr. Rajesh Verma",
    city: "New Delhi",
    location: "Dwarka",
    Specialization: "Cardiologist",
    rating: "4.7",
    experience: "21",
  },
  {
    id: 141,
    name: "Dr. Nandini Gupta",
    city: "Gurgaon",
    location: "Sector 55",
    Specialization: "Gynecologist",
    rating: "4.9",
    experience: "22",
  },
  {
    id: 142,
    name: "Dr. Prakash Singh",
    city: "Noida",
    location: "Sector 18",
    Specialization: "Orthopedic",
    rating: "4.6",
    experience: "19",
  },
  {
    id: 143,
    name: "Dr. Sneha Desai",
    city: "Mumbai",
    location: "Powai",
    Specialization: "Dermatologist",
    rating: "4.8",
    experience: "20",
  },
  {
    id: 144,
    name: "Dr. Arjun Reddy",
    city: "Bangalore",
    location: "Koramangala",
    Specialization: "Neurologist",
    rating: "4.7",
    experience: "18",
  },
  {
    id: 145,
    name: "Dr. Priya Kapoor",
    city: "Chennai",
    location: "T Nagar",
    Specialization: "Pediatrician",
    rating: "4.5",
    experience: "17",
  },
  {
    id: 146,
    name: "Dr. Vikram Joshi",
    city: "Hyderabad",
    location: "Kondapur",
    Specialization: "ENT Specialist",
    rating: "4.6",
    experience: "18",
  },
  {
    id: 147,
    name: "Dr. Rohit Mehra",
    city: "Kolkata",
    location: "Park Street",
    Specialization: "General Physician",
    rating: "4.5",
    experience: "17",
  },
  {
    id: 148,
    name: "Dr. Maya Shah",
    city: "Pune",
    location: "Hinjewadi",
    Specialization: "Dentist",
    rating: "4.8",
    experience: "21",
  },
  {
    id: 149,
    name: "Dr. Akash Singh",
    city: "Ahmedabad",
    location: "Vastrapur",
    Specialization: "Ophthalmologist",
    rating: "4.7",
    experience: "19",
  },
  {
    id: 158,
    name: "Dr. Manish Kapoor",
    city: "New Delhi",
    location: "Saket",
    Specialization: "Cardiologist",
    rating: "4.6",
    experience: "18",
  },
  {
    id: 159,
    name: "Dr. Priya Sharma",
    city: "Gurgaon",
    location: "DLF Phase 4",
    Specialization: "Gynecologist",
    rating: "4.8",
    experience: "20",
  },
  {
    id: 160,
    name: "Dr. Ravi Kumar",
    city: "Noida",
    location: "Sector 62",
    Specialization: "Orthopedic",
    rating: "4.7",
    experience: "19",
  },
  {
    id: 161,
    name: "Dr. Nisha Reddy",
    city: "Mumbai",
    location: "Bandra",
    Specialization: "Dermatologist",
    rating: "4.9",
    experience: "22",
  },
  {
    id: 162,
    name: "Dr. Arvind Gupta",
    city: "Bangalore",
    location: "Indiranagar",
    Specialization: "Neurologist",
    rating: "4.8",
    experience: "20",
  },
  {
    id: 163,
    name: "Dr. Meera Krishnan",
    city: "Chennai",
    location: "Anna Nagar",
    Specialization: "Pediatrician",
    rating: "4.6",
    experience: "18",
  },
  {
    id: 164,
    name: "Dr. Sunil Kumar",
    city: "Hyderabad",
    location: "Madhapur",
    Specialization: "ENT Specialist",
    rating: "4.7",
    experience: "19",
  },
  {
    id: 165,
    name: "Dr. Rahul Bose",
    city: "Kolkata",
    location: "Salt Lake",
    Specialization: "General Physician",
    rating: "4.5",
    experience: "17",
  },
  {
    id: 166,
    name: "Dr. Kavita Sharma",
    city: "Pune",
    location: "Kothrud",
    Specialization: "Dentist",
    rating: "4.7",
    experience: "19",
  },
  {
    id: 167,
    name: "Dr. Siddharth Patel",
    city: "Ahmedabad",
    location: "Maninagar",
    Specialization: "Ophthalmologist",
    rating: "4.6",
    experience: "18",
  },

  {
    id: 168,
    name: "Dr. Neha Kapoor",
    city: "New Delhi",
    location: "Karol Bagh",
    Specialization: "Gynecologist",
    rating: "4.7",
    experience: "16",
  },
  {
    id: 169,
    name: "Dr. Ankit Verma",
    city: "Gurgaon",
    location: "Sector 56",
    Specialization: "Orthopedic",
    rating: "4.6",
    experience: "15",
  },
  {
    id: 170,
    name: "Dr. Prakash Tiwari",
    city: "Noida",
    location: "Sector 62",
    Specialization: "Dermatologist",
    rating: "4.8",
    experience: "18",
  },
  {
    id: 171,
    name: "Dr. Sunil Kumar",
    city: "Mumbai",
    location: "Bandra",
    Specialization: "Neurologist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 172,
    name: "Dr. Anjali Singh",
    city: "Bangalore",
    location: "Indiranagar",
    Specialization: "Pediatrician",
    rating: "4.6",
    experience: "16",
  },
  {
    id: 173,
    name: "Dr. Manoj Gupta",
    city: "Chennai",
    location: "Anna Nagar",
    Specialization: "ENT Specialist",
    rating: "4.8",
    experience: "19",
  },
  {
    id: 174,
    name: "Dr. Priya Reddy",
    city: "Hyderabad",
    location: "Kukatpally",
    Specialization: "General Physician",
    rating: "4.7",
    experience: "18",
  },
  {
    id: 175,
    name: "Dr. Anand Kumar",
    city: "Kolkata",
    location: "Salt Lake",
    Specialization: "Cardiologist",
    rating: "4.9",
    experience: "20",
  },
  {
    id: 176,
    name: "Dr. Sneha Sharma",
    city: "Pune",
    location: "Kothrud",
    Specialization: "Dentist",
    rating: "4.5",
    experience: "14",
  },
  {
    id: 177,
    name: "Dr. Mohan Patel",
    city: "Ahmedabad",
    location: "Satellite",
    Specialization: "Ophthalmologist",
    rating: "4.6",
    experience: "15",
  },

  {
    id: 178,
    name: "Dr. Ritu Singh",
    city: "New Delhi",
    location: "Connaught Place",
    Specialization: "Gynecologist",
    rating: "4.7",
    experience: "16",
  },
  {
    id: 179,
    name: "Dr. Vikas Gupta",
    city: "Gurgaon",
    location: "Sector 23",
    Specialization: "Orthopedic",
    rating: "4.5",
    experience: "14",
  },
  {
    id: 180,
    name: "Dr. Renu Sharma",
    city: "Noida",
    location: "Sector 18",
    Specialization: "Dermatologist",
    rating: "4.8",
    experience: "18",
  },
  {
    id: 181,
    name: "Dr. Sameer Joshi",
    city: "Mumbai",
    location: "Powai",
    Specialization: "Neurologist",
    rating: "4.6",
    experience: "15",
  },
  {
    id: 182,
    name: "Dr. Shalini Singh",
    city: "Bangalore",
    location: "Koramangala",
    Specialization: "Pediatrician",
    rating: "4.8",
    experience: "18",
  },
  {
    id: 183,
    name: "Dr. Karthik Reddy",
    city: "Chennai",
    location: "T Nagar",
    Specialization: "ENT Specialist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 184,
    name: "Dr. Anusha Rao",
    city: "Hyderabad",
    location: "Banjara Hills",
    Specialization: "General Physician",
    rating: "4.9",
    experience: "19",
  },
  {
    id: 185,
    name: "Dr. Surya Mishra",
    city: "Kolkata",
    location: "Park Street",
    Specialization: "Cardiologist",
    rating: "4.6",
    experience: "16",
  },
  {
    id: 186,
    name: "Dr. Preeti Patel",
    city: "Pune",
    location: "Hadapsar",
    Specialization: "Dentist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 187,
    name: "Dr. Arjun Mehta",
    city: "Ahmedabad",
    location: "Bodakdev",
    Specialization: "Ophthalmologist",
    rating: "4.5",
    experience: "14",
  },
  {
    id: 188,
    name: "Dr. Kavita Sharma",
    city: "New Delhi",
    location: "Rohini",
    Specialization: "Gynecologist",
    rating: "4.8",
    experience: "18",
  },
  {
    id: 189,
    name: "Dr. Vishal Khanna",
    city: "Gurgaon",
    location: "Sector 15",
    Specialization: "Orthopedic",
    rating: "4.6",
    experience: "16",
  },
  {
    id: 190,
    name: "Dr. Maya Kapoor",
    city: "Noida",
    location: "Sector 50",
    Specialization: "Dermatologist",
    rating: "4.9",
    experience: "19",
  },
  {
    id: 191,
    name: "Dr. Rajesh Iyer",
    city: "Mumbai",
    location: "Andheri East",
    Specialization: "Neurologist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 192,
    name: "Dr. Nisha Singh",
    city: "Bangalore",
    location: "Whitefield",
    Specialization: "Pediatrician",
    rating: "4.8",
    experience: "18",
  },
  {
    id: 193,
    name: "Dr. Arun Kumar",
    city: "Chennai",
    location: "Adyar",
    Specialization: "ENT Specialist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 194,
    name: "Dr. Ananya Reddy",
    city: "Hyderabad",
    location: "Jubilee Hills",
    Specialization: "General Physician",
    rating: "4.9",
    experience: "19",
  },
  {
    id: 195,
    name: "Dr. Ramesh Iyer",
    city: "Kolkata",
    location: "Howrah",
    Specialization: "Cardiologist",
    rating: "4.6",
    experience: "16",
  },
  {
    id: 196,
    name: "Dr. Priyanka Gupta",
    city: "Pune",
    location: "Aundh",
    Specialization: "Dentist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 197,
    name: "Dr. Rohan Shah",
    city: "Ahmedabad",
    location: "Gurukul",
    Specialization: "Ophthalmologist",
    rating: "4.5",
    experience: "14",
  },
  {
    id: 198,
    name: "Dr. Nidhi Kapoor",
    city: "New Delhi",
    location: "Dwarka",
    Specialization: "Gynecologist",
    rating: "4.8",
    experience: "18",
  },
  {
    id: 199,
    name: "Dr. Ajay Kumar",
    city: "Gurgaon",
    location: "Sector 45",
    Specialization: "Orthopedic",
    rating: "4.6",
    experience: "16",
  },
  {
    id: 200,
    name: "Dr. Neha Verma",
    city: "Noida",
    location: "Sector 62",
    Specialization: "Dermatologist",
    rating: "4.9",
    experience: "19",
  },
  {
    id: 201,
    name: "Dr. Suresh Menon",
    city: "Mumbai",
    location: "Bandra",
    Specialization: "Neurologist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 202,
    name: "Dr. Anjali Reddy",
    city: "Bangalore",
    location: "Indiranagar",
    Specialization: "Pediatrician",
    rating: "4.8",
    experience: "18",
  },
  {
    id: 203,
    name: "Dr. Sanjay Singh",
    city: "Chennai",
    location: "Anna Nagar",
    Specialization: "ENT Specialist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 204,
    name: "Dr. Meena Sharma",
    city: "Hyderabad",
    location: "Kondapur",
    Specialization: "General Physician",
    rating: "4.9",
    experience: "19",
  },
  {
    id: 205,
    name: "Dr. Vikram Patel",
    city: "Kolkata",
    location: "Salt Lake City",
    Specialization: "Cardiologist",
    rating: "4.6",
    experience: "16",
  },
  {
    id: 206,
    name: "Dr. Radha Iyer",
    city: "Pune",
    location: "Kothrud",
    Specialization: "Dentist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 207,
    name: "Dr. Deepak Joshi",
    city: "Ahmedabad",
    location: "Maninagar",
    Specialization: "Ophthalmologist",
    rating: "4.5",
    experience: "14",
  },
  {
    id: 208,
    name: "Dr. Anjali Khanna",
    city: "New Delhi",
    location: "Janakpuri",
    Specialization: "Gynecologist",
    rating: "4.8",
    experience: "18",
  },
  {
    id: 209,
    name: "Dr. Akash Gupta",
    city: "Gurgaon",
    location: "Sector 56",
    Specialization: "Orthopedic",
    rating: "4.6",
    experience: "16",
  },
  {
    id: 210,
    name: "Dr. Priya Singh",
    city: "Noida",
    location: "Sector 82",
    Specialization: "Dermatologist",
    rating: "4.9",
    experience: "19",
  },
  {
    id: 211,
    name: "Dr. Rahul Mehra",
    city: "Mumbai",
    location: "Colaba",
    Specialization: "Neurologist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 212,
    name: "Dr. Reena Kapoor",
    city: "Bangalore",
    location: "Marathahalli",
    Specialization: "Pediatrician",
    rating: "4.8",
    experience: "18",
  },
  {
    id: 213,
    name: "Dr. Prakash Raj",
    city: "Chennai",
    location: "Tambaram",
    Specialization: "ENT Specialist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 214,
    name: "Dr. Geeta Reddy",
    city: "Hyderabad",
    location: "Madhapur",
    Specialization: "General Physician",
    rating: "4.9",
    experience: "19",
  },
  {
    id: 215,
    name: "Dr. Abhishek Banerjee",
    city: "Kolkata",
    location: "Garia",
    Specialization: "Cardiologist",
    rating: "4.6",
    experience: "16",
  },
  {
    id: 216,
    name: "Dr. Prerna Singh",
    city: "Pune",
    location: "Wakad",
    Specialization: "Dentist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 217,
    name: "Dr. Rishi Patel",
    city: "Ahmedabad",
    location: "Vastrapur",
    Specialization: "Ophthalmologist",
    rating: "4.5",
    experience: "14",
  },
  {
    id: 218,
    name: "Dr. Neha Sharma",
    city: "New Delhi",
    location: "Dilshad Garden",
    Specialization: "Gynecologist",
    rating: "4.8",
    experience: "18",
  },
  {
    id: 219,
    name: "Dr. Rohit Kapoor",
    city: "Gurgaon",
    location: "Sector 14",
    Specialization: "Orthopedic",
    rating: "4.6",
    experience: "16",
  },
  {
    id: 220,
    name: "Dr. Ananya Singh",
    city: "Noida",
    location: "Sector 50",
    Specialization: "Dermatologist",
    rating: "4.9",
    experience: "19",
  },
  {
    id: 221,
    name: "Dr. Arvind Menon",
    city: "Mumbai",
    location: "Powai",
    Specialization: "Neurologist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 222,
    name: "Dr. Nisha Reddy",
    city: "Bangalore",
    location: "Whitefield",
    Specialization: "Pediatrician",
    rating: "4.8",
    experience: "18",
  },
  {
    id: 223,
    name: "Dr. Sanjay Kumar",
    city: "Chennai",
    location: "Velachery",
    Specialization: "ENT Specialist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 224,
    name: "Dr. Meenakshi Gupta",
    city: "Hyderabad",
    location: "Hitech City",
    Specialization: "General Physician",
    rating: "4.9",
    experience: "19",
  },
  {
    id: 225,
    name: "Dr. Alok Patel",
    city: "Kolkata",
    location: "Park Street",
    Specialization: "Cardiologist",
    rating: "4.6",
    experience: "16",
  },
  {
    id: 226,
    name: "Dr. Radhika Joshi",
    city: "Pune",
    location: "Baner",
    Specialization: "Dentist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 227,
    name: "Dr. Mohan Iyer",
    city: "Ahmedabad",
    location: "Ghatlodia",
    Specialization: "Ophthalmologist",
    rating: "4.5",
    experience: "14",
  },
  {
    id: 228,
    name: "Dr. Priya Khurana",
    city: "New Delhi",
    location: "Rohini",
    Specialization: "Gynecologist",
    rating: "4.8",
    experience: "18",
  },
  {
    id: 229,
    name: "Dr. Sameer Gupta",
    city: "Gurgaon",
    location: "Sector 23",
    Specialization: "Orthopedic",
    rating: "4.6",
    experience: "16",
  },
  {
    id: 230,
    name: "Dr. Ritu Mehra",
    city: "Noida",
    location: "Sector 137",
    Specialization: "Dermatologist",
    rating: "4.9",
    experience: "19",
  },
  {
    id: 231,
    name: "Dr. Arjun Kapoor",
    city: "Mumbai",
    location: "Malad",
    Specialization: "Neurologist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 232,
    name: "Dr. Anjali Singh",
    city: "Bangalore",
    location: "Koramangala",
    Specialization: "Pediatrician",
    rating: "4.8",
    experience: "18",
  },
  {
    id: 233,
    name: "Dr. Vikram Joshi",
    city: "Chennai",
    location: "Adyar",
    Specialization: "ENT Specialist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 234,
    name: "Dr. Kavita Reddy",
    city: "Hyderabad",
    location: "Gachibowli",
    Specialization: "General Physician",
    rating: "4.9",
    experience: "19",
  },
  {
    id: 235,
    name: "Dr. Aakash Banerjee",
    city: "Kolkata",
    location: "Howrah",
    Specialization: "Cardiologist",
    rating: "4.6",
    experience: "16",
  },
  {
    id: 236,
    name: "Dr. Renuka Singh",
    city: "Pune",
    location: "Aundh",
    Specialization: "Dentist",
    rating: "4.7",
    experience: "17",
  },
  {
    id: 237,
    name: "Dr. Pradeep Patel",
    city: "Ahmedabad",
    location: "Manek Chowk",
    Specialization: "Ophthalmologist",
    rating: "4.5",
    experience: "14",
  },
  {
    id: 238,
    name: "Dr. Nisha Gupta",
    city: "New Delhi",
    location: "Pitampura",
    Specialization: "Gynecologist",
    rating: "4.8",
    experience: "18",
  },
  {
    id: 239,
    name: "Dr. Rohit Khanna",
    city: "Gurgaon",
    location: "DLF Phase 3",
    Specialization: "Orthopedic",
    rating: "4.6",
    experience: "16",
  },
];
